// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0pEBh1eKZEyO0tmeUxz_fafDvgNDIZsw',
    appId: '1:686956780142:web:a9dba4213a202ed269647f',
    messagingSenderId: '686956780142',
    projectId: 'material-max',
    authDomain: 'material-max.firebaseapp.com',
    storageBucket: 'material-max.appspot.com',
    measurementId: 'G-JT3YGLJ7XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ7wX2zTUSnrqacGaYhv7LhOUXz3KOFRo',
    appId: '1:686956780142:android:e7977751e34abf0e69647f',
    messagingSenderId: '686956780142',
    projectId: 'material-max',
    storageBucket: 'material-max.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvYjDlKvT0XqtCK-8mGlvxZLNJx8X8KOQ',
    appId: '1:686956780142:ios:dc426b4a8c4147f769647f',
    messagingSenderId: '686956780142',
    projectId: 'material-max',
    storageBucket: 'material-max.appspot.com',
    iosClientId: '686956780142-35crmkiq5ns2bqg9ijhl09dmvem36urr.apps.googleusercontent.com',
    iosBundleId: 'com.example.material',
  );
}
